### ISSUE TITLE
"unhashable type 'list'" when adding a list to reporter metadata

### ISSUE THREAD

**Issue by agrajag9** [Defense-Cyber-Crime-Center/DC3-MWCP#1]
Is it possible to add a list to reporter metadata? I would expect this to be as simple as outlined below, but apparently it is not.

```
  30         self.nodes = list()
  31         if self.results:
  32             for r in self.results:
  33                 self.nodes.append({"ipv4": str.split(r, '\x00')[0],
  34                                    "pub_key": binascii.hexlify(r[34:])})
  35             self.reporter.add_metadata("other", {"nodes": self.nodes})
```

Error:

```
Could not add object of <type 'list'> to metadata under other using key nodes
```

**Comment by DC3-DCCI** [comment]
At present DC3-MWCP does not support adding metadata in this manner. However, we plan on adding this functionality in the next version of DC3-MWCP.

**Comment by DC3-DCCI** [comment]
For the time being, this ability will not be supported. As a workaround you can add the elements one at a time.
