### ISSUE TITLE
kordesii Reporter incompatible with 1.3.0

### ISSUE THREAD

**Issue by ddash-ct** [Defense-Cyber-Crime-Center/DC3-MWCP#10]
Within `dispatcher`, importing the `kordesii reporter` is not compatible with the updates for `kordesii 1.3.0`.

Line 23 would need to be `from kordesii.reporter import Reporter as kordesiireporter`, but this would not provide backwards compatibility with `kordesii < 1.3.0`

**Comment by DC3-DCCI** [comment]
This has been fixed in version 2.0.2. DC3-MWCP only supports kordesii >= 1.4.0 going forward.
