### ISSUE TITLE
Error installing with pip

### ISSUE THREAD

**Issue by jdsnape** [Defense-Cyber-Crime-Center/DC3-MWCP#13]
On a fresh Debian install, I get an error when trying to install with pip as it seems to be no longer available in the repository:

sudo pip install mwcp
Collecting mwcp
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/mwcp/

**Comment by DC3-DCCI** [comment]
MWCP is currently not available on PyPi.org.  You will have to clone the repository first to install it.

**Comment by jdsnape** [comment]
OK, that’s what I’ve done. The README says

> pip install mwcp

As an install method so might be worth updating?

**Comment by DC3-DCCI** [comment]
Thank you for pointing that out.  We will look at getting this updated or made available on PyPi in the near future.

**Comment by doomedraven** [comment]
why just not to use `pip install git+https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP`

**Comment by DC3-DCCI** [comment]
MWCP is now on PyPi
