### ISSUE TITLE
Fields in malwareconfigreporter and fields.json do not match, using certain fields results in error.

### ISSUE THREAD

**Issue by kevoreilly** [Defense-Cyber-Crime-Center/DC3-MWCP#2]
For example, malwareconfigreporter.py contains the fields "registrykeyvalue", "registrykey", "registryvalue", "key", but these do not match the fields in fields.json: "registrydata", "registrypath", "registrypathdata". Using any of these fields with 'add_metadata' results in "Error adding metadata because <field> is not an allowed key".
Should the fields in fields.json, or a subset thereof, not match those in malwareconfigreporter.py?

**Comment by DC3-DCCI** [comment]
Should be resolved by c67d5395a437b4a58cd1c8f6b33f4eaee1decbd7
