### ISSUE TITLE
No support for python3

### ISSUE THREAD

**Issue by mlaferrera** [Defense-Cyber-Crime-Center/DC3-MWCP#3]
Would a PR for python3 support be desired?

**Comment by DC3-DCCI** [comment]
A pull request to add Python 3 support would give valuable flexibility to the framework and be desired. The code just needs to remain backwards compatible with Python 2.7.

**Comment by sroberts** [comment]
I would very much like a move to Python3.

**Comment by mlaferrera** [comment]
Initial python3 support is at https://github.com/mlaferrera/DC3-MWCP. I don't have many (read: None) test cases, so I am not sure if it is entirely working as intended right now.

**Comment by mlaferrera** [comment]
The PR was pushed last July. Any chance it will be merged?

**Comment by DC3-DCCI** [comment]
These changes have now been merged.
