### ISSUE TITLE
poshdeob.py detected as malicious (VirusTotal)

### ISSUE THREAD

**Issue by foxalfabravo** [Defense-Cyber-Crime-Center/DC3-MWCP#32]
On VT today, 
Kaspersky: HEUR:Trojan.PowerShell.Generic
Bkav Pro: ASP.Webshell
https://www.virustotal.com/gui/file/c044aa7e5851f152a734265e00677bd667dca5cad37a80335c4433d92b74b17b

**Comment by DC3-DCCI** [comment]
Thank you for letting us know about this.  The Kaspersky finding is a false positive associated with examples within docstrings so we are going to see if there is a clean way to resolve this without making the internal documentation worse.  Bkav Pro is a false positive based on a list of lookup terms that can't be changed.

**Comment by DC3-DCCI** [comment]
The 3.5.0 release has resolved the finding from Kaspersky, but the false positive is still present from Bkav Pro.  This issue is being closed as making a change to address the false positive would reduce MWCP's functionality.
